apiVersion: v1
kind: Namespace
metadata:
  name: dharmaguard
  labels:
    name: dharmaguard
    environment: production
    app.kubernetes.io/name: dharmaguard
    app.kubernetes.io/version: "1.0.0"
---
apiVersion: v1
kind: Namespace
metadata:
  name: dharmaguard-monitoring
  labels:
    name: dharmaguard-monitoring
    environment: production
---
apiVersion: v1
kind: Namespace
metadata:
  name: dharmaguard-dev
  labels:
    name: dharmaguard-dev
    environment: development
